import streamlit as st
import datetime
import sys, os
sys.path.insert(0, os.path.join(os.path.dirname(__file__), ".."))
from theme import ARCTIC_CSS

st.set_page_config(page_title="Generate Report", page_icon="📄", layout="wide")
st.markdown(ARCTIC_CSS, unsafe_allow_html=True)
st.title("📄 Generate Fairness Report")
st.markdown("Configure and download a customised fairness audit report.")

c1, c2 = st.columns(2)
with c1:
    report_type = st.selectbox("Report Type",
        ["Executive Summary","Technical Analysis","Mitigation Plan","Full Audit Report"])
    sections = st.multiselect("Include Sections",
        ["Fairness Metrics","Proxy Variables","Mitigation Results",
         "Cross-Dataset Validation","Recommendations","Technical Details","Governance Framework"],
        default=["Fairness Metrics","Mitigation Results","Recommendations"])
with c2:
    org    = st.text_input("Organisation Name", "UK Financial Services Organisation")
    author = st.text_input("Reviewer / Analyst", "HR Analytics Team")
    date   = st.date_input("Report Date", value=datetime.date.today())
    model  = st.selectbox("Primary Model", ["XGBoost","Random Forest","Logistic Regression","All Models"])

st.divider()

if st.button("📄 Generate Report", type="primary"):
    r = f"""# Algorithmic Fairness Audit Report
**Type:** {report_type} | **Organisation:** {org} | **Reviewer:** {author} | **Date:** {date} | **Model:** {model}

---

## Executive Summary

This report presents findings from an algorithmic fairness audit of ML models used in HR recruitment
screening. The four-fifths rule (DIR ≥ 0.8) is applied as a practical benchmark drawn from the US
EEOC Uniform Guidelines on Employee Selection Procedures. It is not a statutory threshold under the
Equality Act 2010 — organisations must also demonstrate that any potentially disadvantaging practice
is a proportionate means of achieving a legitimate aim under Section 19. The Data (Use and Access)
Act 2025 (DUAA) has also updated the UK automated decision-making framework. Three classifiers were
evaluated: Logistic Regression, Random Forest, and XGBoost. All exhibited consistent negative SPD
across protected groups.

"""
    if "Fairness Metrics" in sections:
        r += """---\n## Fairness Metrics Summary\n
| Classifier | Gender SPD | Gender DIR | Education DIR | F1 Score |
|------------|------------|------------|---------------|----------|
| Logistic Regression | -0.0369 | 0.858 | 0.536 | 79.0% |
| Random Forest | -0.0716 | 0.817 | 0.700 | 84.6% |
| XGBoost | -0.0839 | 0.807 | 0.727 | 86.0% |

Education bias is the most severe, with DIR as low as 0.536 — well below the 0.80 four-fifths rule practical benchmark.\n"""

    if "Proxy Variables" in sections:
        r += """\n---\n## Proxy Variable Analysis (SHAP)\n
RecruitmentStrategy_1 has the highest average SHAP value (1.001) across all models — outweighing
all job-relevant predictors. This recruitment channel variable embeds indirect discrimination if
sourcing channels are demographically skewed.\n"""

    if "Mitigation Results" in sections:
        r += """\n---\n## Mitigation Results\n
| Technique | Gender SPD | F1 Score | SPD Improved? |
|-----------|------------|----------|----------------|
| Baseline | -0.0839 | 86.0% | — |
| Reweighting | -0.0716 | 85.4% | ✅ Yes |
| ExponentiatedGradient | -0.0187 | 78.9% | ✅ Yes |
| ThresholdOptimizer | -0.0689 | 84.7% | ✅ Yes |

ThresholdOptimizer is recommended for compliance-oriented deployment.\n"""

    if "Cross-Dataset Validation" in sections:
        r += """\n---\n## Cross-Dataset Validation\nNegative SPD confirmed across both datasets (n=1,500 and n=225). Findings generalise.\n"""

    if "Recommendations" in sections:
        r += """\n---\n## Recommendations\n
1. Implement ThresholdOptimizer for Random Forest and XGBoost models\n
2. Audit RecruitmentStrategy_1 for proxy discrimination\n
3. Establish quarterly fairness review cycles\n
4. Develop Model Transparency Cards for all deployed classifiers\n
5. Align AI governance with FCA conduct standards and GDPR\n"""

    if "Governance Framework" in sections:
        r += """\n---\n## Socio-Technical Governance Framework\n
| Layer | Focus | Key Actions |
|-------|-------|-------------|
| Technical | Algorithm fairness | ThresholdOptimizer, SHAP monitoring |
| Organisational | HR policy | Bias audit schedules, diverse sourcing |
| Regulatory | Legal compliance | Equality Act 2010, GDPR, FCA standards |
| Human Oversight | Transparency | Recruiter review, candidate appeals |\n"""

    if "Technical Details" in sections:
        r += """\n---\n## Technical Details\n
- Models: Logistic Regression, Random Forest, XGBoost\n
- Libraries: AIF360, Fairlearn, SHAP (TreeExplainer)\n
- Platform: Google Colab (Python 3.11)\n
- Primary Dataset: 1,500 records, 31% hire rate\n
- Secondary Dataset: 225 records, 33% hire rate\n
- SHAP Fix: RF 3D array resolved via shap_values[:, :, 1]\n"""

    r += f"\n---\n*Generated by FairHire Audit Tool · {date} · University of Greater Manchester*\n"

    st.success("✅ Report generated successfully!")
    st.download_button("⬇️ Download Report (Markdown)", r,
                       f"fairness_report_{date}.md", "text/markdown")
    with st.expander("Preview Report"):
        st.markdown(r)
